#!/bin/bash

repo_name=$1
#token=`cat /home/theo/docs/GitHubAPI/repo_token`
#auth_header='Authorization: token "'$token'"'
#data='{"name": "'$repo_name'"}'
#url='https://api.github.com/user/repos'

#curl -H '$auth_header' -d $data -X POST $url

curl -H "Authorization: token `cat /home/theo/docs/github-api/repo_token`" \
     -d '{"name": "'$repo_name'"}' \
     -X POST \
     https://api.github.com/user/repos

#git remote add origin "git@github.com:soraismus/'$repo_name'.git"
#git push -u origin master
