#!/bin/bash

repo="$1"
token="$( cat "$HOME/docs/github-api/repo_token" )"

curl -H "Authorization: token $token" \
     -d '{"name": "'$repo'"}' \
     -X POST \
     https://api.github.com/user/repos

unset repo token
