#!/usr/src/ruby-2.0.0-p195/ruby
require "selenium-webdriver"

driver = Selenium::WebDriver.for :firefox
driver.get "https://www.pandora.com"

sign_in_link = driver.find_elements_by_link_text( "sign in")
sign_in_link.click

email_field = driver.find_element(:name => "email")
email_field.send_keys "decimus_lupus@yahoo.com"

password_field = driver.find_element(:name => "password")
password_field.send_keys "rufusx"

remember_box = driver.find_element(:name => "remember")
remember_box.click

sign_in_btn = driver.find_element(:value => "Sign in")
sign_in_btn.submit

# 
# <a href="/account/sign-in" address="true">
#    Sign in
# </a>
#
# link = Selenium::Link.by_text(/browser/, /text/)
# link.go
#
#
# find_element_by_xpath("//div/td[1]")
# find_element_by_partial_link_text("sign in")
# find_elements_by_link_text("sign in"
