#!/bin/sh
# Open connection to Starbucks
nmcli con up id attwifi

# Start a new Firefox window and focus on url bar
# xdotool key super+shift+2 ctrl+l

# Go to example.com
# xdotool type "example.com"
# xdotool key Return

# Start a new Firefox window and go to example.com
firefox --new-window npr.org

# Move mouse to 'Agree' button
CURRENT=$(xdotool getwindowfocus)
xdotool mousemove --window $CURRENT --sync 100 290 

# Sleep until connection; then click
xdotool sleep 5
xdotool click 1

# Connect to vpn
nmcli con up id "PIA - US Texas"
