#!/bin/bash

if [[ $# == 0 || $# == 1 ]]; then
	echo "  This script requires one of two patterns:"
	echo "  1) filename tagname"
	echo "  2) --all filename"
	exit 1;
fi

if [ -z "$TAGDIR" ]; then
  echo "  The variable TAGDIR has not been set to '$HOME/.tags' or exported"
	exit 2;
fi

# REF is set to the inode of filename
#REF="$( ls -iL "$1" | awk '{print $1}' )"

if [[ "$1" = --all ]]; then
	REF="$( ls -iL "$2" | awk '{print $1}' )"
  find "$TAGDIR" -name "$REF" -delete
	echo "  All tags for '$2' have been deleted"
	exit 0;
else
	REF="$( ls -iL "$1" | awk '{print $1}' )"
	rm "$TAGDIR/$2/$REF"
	echo " The tag '$2' no longer applies to '$1'"
	exit 0;
fi
